[project]
name = "flx"
version = "0.2.0"
description = "A Lua-config-driven application launcher and local bin"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Finn Mallon"},
]
keywords = ["launcher", "application-launcher", "cli", "lua", "shell"]
dependencies = [
    "Pillow",
    "pywebview[qt]",
]

[project.scripts]
flx = "flx.main:main"

[tool.setuptools.package-data]
flx = [
    "scripts/*.lua",
    "gui/HTML/*.html",
    "gui/CSS/*.css",
    "gui/JS/*.js",
]
